/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chevy' at '2017/5/26 上午 9:19' with Gradle 3.0
 *
 * @author chevy, @date 2017/5/26 上午 9:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
